const projectsData = [
    {
        id: 1,
        title: "Contact List",
        image: "/images/projects/1.png",
        tag: ["All", "React"],
        gitUrl: "https://github.com/himanshu-hota/contacts",
        previewUrl: "https://main--jocular-elf-15d6df.netlify.app/",
        style: "shadow-green-900",
    },
    {
        id: 2,
        title: "Netflix",
        image: "/images/projects/2.png",
        tag: ["All", "React"],
        gitUrl: "https://github.com/himanshu-hota/Netflix-clone",
        previewUrl: "https://netflix-clone-3bbfc.web.app/",
        style: "shadow-blue-500",
    },
    {
        id: 3,
        title: "NFT Marketplace",
        image: "/images/projects/3.png",
        tag: ["All", "React"],
        gitUrl: "https://github.com/himanshu-hota/nft-marketplace",
        previewUrl: "https://nft-market-bc1da.web.app/",
        style: "shadow-yellow-500",
    },
    {
        id: 4,
        title: "E-Commerce Dashboard",
        image: "/images/projects/4.png",
        tag: ["All", "React"],
        gitUrl: "https://github.com/himanshu-hota/ecommerce",
        previewUrl: "https://e-com-c6253.web.app/",
        style: "shadow-blue-600",
    },
    {
        id: 5,
        title: "XMDB",
        image: "/images/projects/5.png",
        tag: ["All", "Javascript"],
        gitUrl: "https://github.com/himanshu-hota/XMDB",
        previewUrl: "https://himanshu-hota.github.io/Big-barber/",
        style: "shadow-white",
    },
    {
        id: 6,
        title: "Hair Studio",
        image: "/images/projects/6.png",
        tag: ["All", "Javascript"],
        gitUrl: "https://github.com/himanshu-hota/Big-barber",
        previewUrl: "https://himanshu-hota.github.io/Big-barber/",
        style: "shadow-sky-400",
    },
    {
        id: 7,
        title: "Gravero",
        image: "/images/projects/7.png",
        tag: ["All", "Javascript"],
        gitUrl: "https://github.com/himanshu-hota/Gravero",
        previewUrl: "https://himanshu-hota.github.io/Gravero/",
        style: "shadow-gray-400",
    },
    {
        id: 8,
        title: "Shoe Store",
        image: "/images/projects/8.png",
        tag: ["All", "Next JS"],
        gitUrl: "https://github.com/himanshu-hota/shoe-store-frontend",
        previewUrl: "https://shoe-store-frontend-orpin.vercel.app/product/air-jordan-6-retro",
        style: "shadow-purple-400",
    },
    {
        id: 9,
        title: "Portfolio",
        image: "/images/projects/9.png",
        tag: ["All", "Next JS"],
        gitUrl: "https://github.com/himanshu-hota/nextjs-portfolio",
        previewUrl: "https://nextjs-portfolio-nu-tawny.vercel.app/",
        style: "shadow-sky-400",
    },
    {
        id: 10,
        title: "Supereme 1.0 & Striver A2Z",
        image: "/images/projects/10.png",
        tag: ["All", "DSA"],
        gitUrl: "https://github.com/himanshu-hota/SupremeBatch",
        previewUrl: "https://github.com/himanshu-hota/SupremeBatch",
        style: "shadow-green-400",
    },

];